3-2-应用软件开发实践/83012852源码完整/EasyWriting/EasyWriting/urls.py
from django.contrib import admin
from django.urls import include, path


# 注意要引入自己的 views

urlpatterns = [
    path('', include('user.urls')),
    path('admin/', admin.site.urls),
    path('writing/', include('writing.urls')),
]

3-2-应用软件开发实践/83012852源码完整/EasyWriting/user/urls.py
from django.urls import path

from . import views

app_name = 'user'
urlpatterns = [
    # path('admin/', admin.site.urls),
    path('', views.loginView, name='login'),
    path('login/', views.loginView, name='login'),
    path('register/', views.registerView,name='register'),
    path('logout/', views.logoutView,name='logout'),
]

3-2-应用软件开发实践/83012852源码完整/EasyWriting/writing/urls.py
from django.urls import path

from . import views

app_name = 'writing'
urlpatterns = [
    # 页面

    path('', views.index, name='index'),  # 总览
    path('list/', views.writing, name='list'),  # 编辑
    path('<int:article_id>/', views.edit, name='edit'),  # 编辑
    path('create/', views.create, name='create'),  # 新建
    path('help/', views.help, name='help'),  # 帮助
    path('about/', views.about, name='about'),  # 关于
    path('user/', views.user, name='user'),  # 用户信息

    # 操作
    path('add/', views.add, name='add'),  # 增
    path('update/', views.update, name='update'),  # 改
    path('query/', views.query, name='query'),  # 查
    path('delete/', views.delete, name='delete'),  # 删

    path('user_update/', views.user_update, name='user_update'),  # 更新用户信息

    path('generate/', views.generate, name='generate'),  # 更新用户信息
]

3-2-应用软件开发实践/83012852源码完整/EasyWriting/user/models.py
from django.db import models

# Create your models here.

3-2-应用软件开发实践/83012852源码完整/EasyWriting/writing/models.py
import datetime

from django.contrib import admin
from django.db import models
from django.utils import timezone


class Article(models.Model):
    title = models.CharField(max_length=50)
    abstract = models.TextField(max_length=300)  # 摘要
    body = models.TextField()  # 正文（因为文章的正文字数会很多，所以需要使用该类TextField）
    keyword = models.CharField(max_length=40)
    category = models.CharField(max_length=5)  # 类型
    author = models.CharField(max_length=10)  # 作者
    create_time = models.DateTimeField(auto_now_add=True)  # 创建时间
    update_time = models.DateTimeField(auto_now=True)  # 更新时间

    def __str__(self):
        return self.title

    def was_updated_recently(self):
        now = timezone.now()
        return now - datetime.timedelta(days=7) <= self.update_time <= now

    @admin.display(boolean=True, ordering='create_time', description='created recently?', )
    def was_created_recently(self):
        now = timezone.now()
        return now - datetime.timedelta(days=7) <= self.create_time <= now

3-2-应用软件开发实践/83012852源码完整/EasyWriting/user/views.py
from django.http import HttpResponse
from django.shortcuts import render, redirect
from django.contrib.auth.models import User
from django.contrib.auth import login, logout, authenticate


# Create your views here.
# 登录
def loginView(request):
    if request.user.is_authenticated:
        return redirect("/writing")
    else:
        if request.method == "POST":
            username = request.POST.get("username")
            password = request.POST.get("password")
            if User.objects.filter(username=username):
                user = authenticate(username=username, password=password)
                if user:
                    login(request, user)
                    request.session['username'] = username
                    msg = "登录成功"
                    # print(request.session.get('username'))
                    request.session.set_expiry(86400)
                    # 保存一天的session
                    return redirect("/writing")
                else:
                    msg = "用户名密码错误，或被限制登录"
            else:
                msg = "用户名不存在"
    return render(request, "user/login.html", locals())


# 注册
def registerView(request):
    if request.method == "POST":
        username = request.POST.get("username")
        password = request.POST.get("password")
        email = request.POST.get("email")
        if User.objects.filter(username=username):
            msg = "用户名已存在"
        else:
            user = User.objects.create_user(username=username, password=password, email=email)
            msg = "注册成功"
            return redirect("/login/")
    return render(request, "user/register.html", locals())


def logoutView(request):
    logout(request)
    return redirect('user:login')

3-2-应用软件开发实践/83012852源码完整/EasyWriting/writing/views.py
import os.path
import re

from django.contrib.auth.decorators import login_required
from django.http import HttpResponse, JsonResponse
from django.shortcuts import render

from .models import Article

import datetime

import requests
from bs4 import BeautifulSoup

from wordcloud import WordCloud

from writing.generate_title import *


@login_required(login_url='/login/')
def writing(request):
    username = request.session.get('username')
    return render(request, 'writing/writing.html', locals())


@login_required(login_url='/login/')
def edit(request, article_id):
    try:
        username = request.session.get('username')
        article = Article.objects.get(pk=article_id)
        return render(request, 'writing/edit.html', locals())
    except:
        return HttpResponse("fail")


@login_required(login_url='/login/')
def update(request):
    try:
        selected_article = Article.objects.get(pk=request.POST['id'])
        selected_article.abstract = request.POST['abstract']
        selected_article.title = request.POST['title']
        selected_article.body = request.POST['body']
        selected_article.category = request.POST['category']
        selected_article.keyword = request.POST['keyword']
        selected_article.save()
        return HttpResponse("success")
    except:
        return HttpResponse("fail")


@login_required(login_url='/login/')
def query(request):
    # try:
    pageNo = int(request.POST.get("pageNo"))
    pageSize = int(request.POST.get("pageSize"))
    left = (pageNo - 1) * pageSize
    right = pageNo * pageSize
    type = request.POST.get("search_type")
    search = request.POST.get("search")
    category = request.POST.get("search_category")
    if not category:
        category = ""
    if type == 'title':
        article = Article.objects.filter(author=request.session.get('username'), category__contains=category,
                                         title__contains=search)
    elif type == 'abstract':
        article = Article.objects.filter(author=request.session.get('username'), category__contains=category,
                                         abstract__contains=search)
    elif type == 'body':
        article = Article.objects.filter(author=request.session.get('username'), category__contains=category,
                                         body__contains=search)
    else:
        article = Article.objects.filter(author=request.session.get('username'), category__contains=category)
    context = {
        "code": 0,
        "msg": "",
        "count": article.count(),
        "data": list(article[left:right].values())
    }
    return JsonResponse(context)


# except:
#     return HttpResponse("fail")


@login_required(login_url='/login/')
def delete(request):
    if request.GET.get('article_id'):
        Article.objects.filter(pk=request.GET.get('article_id')).delete()
        return HttpResponse("success")
    else:
        return HttpResponse("fail")


@login_required(login_url='/login/')
def add(request):
    try:
        Article.objects.create(title=request.POST.get('title'),
                               author=request.POST.get('author'),
                               abstract=request.POST.get('abstract'),
                               category=request.POST.get('category'),
                               body=request.POST.get('body'),
                               keyword=request.POST.get('keyword'))
        return HttpResponse("success")
    except:
        return HttpResponse("fail")


@login_required(login_url='/login/')
def create(request):
    # try:
    username = request.session.get('username')
    return render(request, 'writing/create.html', locals())
    # except:
    #     return HttpResponse("fail")


@login_required(login_url='/login/')
def index(request):
    username = request.session.get('username')

    # 近七天的个人新建和全站新建文章数量统计
    data_user = []
    data_all = []
    for i in range(-6, 1):
        start = datetime.date.today() + datetime.timedelta(days=i)
        end = datetime.date.today() + datetime.timedelta(days=i + 1)
        data_user.append(Article.objects.filter(create_time__range=(start, end), author=username).count())
        data_all.append(Article.objects.filter(create_time__range=(start, end)).count())
    list_recent_a_week = [(datetime.date.today() + datetime.timedelta(days=i)).strftime('%m-%d') for i in range(-6, 1)]

    # 所有时间全站人一天中分时段活跃情况（创建文章数量）
    data_hour_all = []
    for i in range(0, 24, 2):
        data_hour_all.append(Article.objects.filter(create_time__hour=i).count())

    # 近七天所有人文章内容关键词统计云图，一天只绘制一个，减少计算量
    today = datetime.date.today().strftime("%y%m%d")
    static_root = "static"
    filename = static_root + "/media/web/wordcloud/wordcloud_" + today + ".png"
    if not os.path.exists(filename):
        start = datetime.date.today() - datetime.timedelta(days=7)
        end = datetime.date.today()
        all_text = list(Article.objects.filter(create_time__range=(start, end)).values_list("keyword", flat=True))
        text = ','.join(all_text)

        wordcloud = WordCloud(
            background_color="white",
            max_words=50,
            width=1200,
            height=800,
            # mask=background,
            font_path= static_root + '/media/font/font.TTF'
        )
        if text == "":
            text = "无写作内容"
        wordcloud.generate(text)
        wordcloud.to_file(static_root + "/media/web/wordcloud/wordcloud_" + datetime.date.today().strftime("%y%m%d") + ".png")

    # 爬虫配置
    kv = {'user-agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) '
                        'Chrome/102.0.5005.63 Safari/537.36 Edg/102.0.1245.30',
          'cookie': 'SINAGLOBAL=8134414668216.274.1617202890239; _td=dec95211-6683-4c56-af9e-34daaf9b5736; UM_distinctid=17dc1e39cc23f6-0218421d30c2da-5919195f-144000-17dc1e39cc33bf; SUBP=0033WrSXqPxfM725Ws9jqgMF55529P9D9WF4zQvjY2m03mIaCG-T9Czg5JpX5KMhUgL.FozE1h5c1h5peoB2dJLoIE-_i--RiKn0i-2pi--ci-2XiK.Ei--ci-2XiK.Ei--ci-2XiK.E; ALF=1686311074; SSOLoginState=1654775075; SCF=Atb-Mc8iaCTfdApxnkiAB6pnyEQL1rfaqKDcXxNLWovajryYf-QIWdgU7qPkST0r-pq-NBW3xGpad6NlUnczEEE.; SUB=_2A25Ppa1zDeRhGeRM41IX-C7NyTiIHXVs0pm7rDV8PUNbmtB-LRXYkW9NU90B-QOoQeT-ZgXjkiao3zWB7Clb_NAC; _s_tentry=login.sina.com.cn; Apache=7749300227723.565.1654775077437; ULV=1654775077478:34:2:2:7749300227723.565.1654775077437:1654665969982; UOR=,,www.baidu.com'}
    SEARCH_NUM = 20

    # 百度
    url = "https://top.baidu.com/board?tab=realtime"
    selector = 'div.content_1YWBm'
    response = requests.get(url, headers=kv).text
    baidu = BeautifulSoup(response, features="lxml").select(selector + " > a")[:SEARCH_NUM]
    baidu1 = BeautifulSoup(response, features="lxml").select(selector + " div.c-single-text-ellipsis")[:SEARCH_NUM]
    baidu_link_and_title = []
    for i in range(SEARCH_NUM):
        baidu_link_and_title.append([baidu[i].get("href"), baidu1[i].get_text().strip()])


    # bilibili
    url = "https://www.bilibili.com/v/popular/rank/all"
    selector = 'div.content > .info > a'
    response = requests.get(url, headers=kv).text
    bili = BeautifulSoup(response, features="lxml").select(selector)[:SEARCH_NUM]
    bili_link_and_title = []
    for bl in bili:
        bili_link_and_title.append([bl.get("href")[2:], bl.get_text()])

    # 矿大
    url = "http://xwzx.cumt.edu.cn/513/list.htm"
    selector = 'span.Article_Title > a'
    response = requests.get(url, headers=kv)
    response.encoding = response.apparent_encoding
    response = response.text
    cumt = BeautifulSoup(response, features="lxml").select(selector)[:20]
    cumt_link_and_title = []
    for c in cumt:
        cumt_link_and_title.append([c.get("href"), c.get_text()])

    # 全站文章类型统计
    type_list = ['党建', '科技', '国际', '文化', '经济']
    type_num = []
    for type in type_list:
        type_num.append(Article.objects.filter(category=type).count())
    # print(type_num)

    return render(request, 'writing/index.html', locals())


@login_required(login_url='/login/')
def help(request):
    username = request.session.get('username')
    return render(request, 'writing/help.html', locals())


@login_required(login_url='/login/')
def about(request):
    username = request.session.get('username')
    return render(request, 'writing/about.html', locals())


@login_required(login_url='/login/')
def user(request):
    user = request.user
    return render(request, 'writing/user.html', locals())


@login_required(login_url='/login/')
def user_update(request):
    msg = ''
    old_password = request.POST.get('old_password')
    new_password = request.POST.get('new_password')
    repeat_password = request.POST.get('repeat_password')
    # print(old_password, new_password, repeat_password)
    # 检查旧密码是否正确
    if request.user.check_password(old_password):
        if not new_password:
            msg = '新密码不能为空'
        elif new_password != repeat_password:
            msg = '两次密码不一致'
        elif old_password == new_password:
            msg = '新旧密码相同'
        else:
            request.user.set_password(new_password)
            request.user.save()
            msg = 'success'
    else:
        msg = '原密码输入错误'
    return HttpResponse(msg)


def generate(request):
    text = request.POST.get('content')
    text = re.sub(r'(\\n)|(<.*?>)', '', text)
    text = re.sub(r"\s+", " ", text)
    print(text)

    summary = get_summer(text)
    print(summary)
    keyword = get_key(text)
    print(keyword)
    title = get_title(text)
    print(title)

    code = 100
    msg = {
        'code': code,
        'title': title,
        'summary': summary,
        'keyword': keyword
    }

    # msg = {
    #     'title': "title",
    #     'summary': "summary",
    #     'keyword': "keyword"
    # }
    return JsonResponse(msg)

3-2-应用软件开发实践/83012852源码完整/EasyWriting/writing/templates/writing/create.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>文章新建</title>
</head>

{#  注意引入文件的方式  #}
{% load static %}
<script src="{% static 'scripts/jquery-1.7.2.js' %}"></script>
<link rel="stylesheet" type="text/css" href="{% static 'layui/css/layui.css' %}">
<body>
<div class="layui-header">
    <ul class="layui-nav">
        <li class="layui-nav-item"><a href="{% url 'writing:index' %}">主页</a></li>
        <li class="layui-nav-item"><a href="{% url 'writing:list' %}">写作台</a></li>
        <li class="layui-nav-item"><a href="{% url 'writing:help' %}">使用指南</a></li>
        <li class="layui-nav-item"><a href="{% url 'writing:about' %}">关于</a></li>
    </ul>
    <ul class="layui-nav layui-layout-right">
        <li class="layui-nav-item layui-hide layui-show-md-inline-block">
            <a href="javascript:;">
                <img id='iconNav' src="{% static 'media/web/icon.jpg' %}" class="layui-nav-img">
                欢迎您，{{ username }}！
            </a>
            <dl class="layui-nav-child">
                <dd><a href="{% url 'writing:user' %}">修改信息</a></dd>
                <dd><a href="{% url 'user:logout' %}">退出登录</a></dd>
            </dl>
        </li>
    </ul>
</div>
<div style="margin: 10px">
    <blockquote class="layui-elem-quote layui-text">
        这里可以新建一篇文章。
    </blockquote>

    <fieldset class="layui-elem-field layui-field-title" style="margin-top: 20px;">
        <legend>文章新建</legend>
    </fieldset>

    <div class="layui-bg-gray" style="padding: 20px;">

        <form action="" class="layui-form" lay-filter="edit">
            {% csrf_token %}
            <div class="layui-row layui-col-space15">

                <div class="layui-col-md12">
                    <div class="layui-card">
                        <div class="layui-card-header">文章属性</div>
                        <div class="layui-card-body">
                            <div class="layui-form-item">
                                <div class="layui-inline">
                                    <label class="layui-form-label">作者名</label>
                                    <div class="layui-input-inline">
                                        <input type="text" name="author" value="{{ username }}"
                                               class="layui-input"
                                               disabled
                                               style="background-color: #C9C9C9; color: #009f95">
                                    </div>
                                </div>
                            </div>
                            <div class="layui-form-item">

                            </div>

                            <div class="layui-form-item">
                                <label class="layui-form-label">标题</label>
                                <div class="layui-input-block">
                                    <input type="text" name="title" lay-verify="title" value=""
                                           placeholder="请输入标题" class="layui-input">
                                </div>
                            </div>

                            <div class="layui-form-item layui-form-text">
                                <label class="layui-form-label">摘要</label>
                                <div class="layui-input-block">
                                    <textarea name="abstract" lay-verify="abstract" placeholder="请输入内容"
                                              class="layui-textarea"></textarea>
                                </div>
                            </div>

                            <div class="layui-form-item">
                                <label class="layui-form-label">类型</label>
                                <div class="layui-input-block">
                                    <select name="category">
                                        <option value="党建" selected="">党建</option>
                                        <option value="科技">科技</option>
                                        <option value="国际">国际</option>
                                        <option value="文化">文化</option>
                                        <option value="经济">经济</option>
                                    </select>
                                </div>
                            </div>

                            <div class="layui-form-item">
                                <label class="layui-form-label">关键词</label>
                                <div class="layui-input-block">
                                    <input type="text" name="keyword" value=""
                                           placeholder="关键词" class="layui-input">
                                </div>
                            </div>

                            <div class="layui-form-item">
                                <div class="layui-input-block">
                                    <button type="button" id='back'
                                            class="layui-btn layui-btn-primary layui-border-green">返回列表
                                    </button>
                                    <button type="button" class="layui-btn layui-btn-normal"
                                            id="LAY-component-form-setval">AI生成
                                    </button>
                                    <button type="submit" class="layui-btn" lay-submit="" lay-filter="btn_edit">立即提交
                                    </button>
                                </div>
                            </div>

                        </div>
                    </div>
                </div>
            </div>

            <div class="layui-col-md12">
                <div class="layui-card">
                    <div class="layui-card-header">文章新建</div>
                    <div class="layui-card-body">
                            <textarea name="body" id="article_edit" lay-verify="content"
                                      style="display: none;"></textarea>
                    </div>
                </div>
            </div>
        </form>
    </div>
</div>


</body>
<script src="{% static 'layui/layui.js' %}"></script>

<script>
    layui.use(['form', 'layedit'], function () {
        var form = layui.form
            , layer = layui.layer
            , layedit = layui.layedit;


        //layedit.set一定要放在 layedit.build 前面，否则配置全局接口将无效。

        //建立编辑器
        var editIndex = layedit.build('article_edit', {
            tool: ['left', 'center', 'right', '|', 'strong', 'italic', 'underline', 'del']
        });

        //自定义验证规则
        form.verify({
            title: function (value) {
                if (value.length < 4) {
                    return '标题至少得4个字符嗷';
                } else if (value.length > 60) {
                    return '标题最多60个字符嗷';
                }
            },
            abstract: function (value) {
                if (value.length < 5) {
                    return '摘要至少得2个字符嗷';
                } else if (value.length > 500) {
                    return '摘要最多500个字符嗷';
                }
            },
            content: function (value) {
                return layedit.sync(editIndex);
            }

        });


        //提交事件
        form.on('submit(btn_edit)', function (data) {
            {#layer.alert(JSON.stringify(data.field), {#}
            {#    title: '最终的提交信息'#}
            {# })#}
            $.ajax({
                url: "{% url 'writing:add'%}",
                type: 'post',
                data: data.field,
                dataType: "text",
                success: function (result) {
                    // console.log(data)
                    console.log("result: " + result)
                    if (result == 'success') {
                        layer.msg('提交成功', {icon: 1});
                    } else {
                        layer.msg('提交失败', {icon: 2});
                    }
                }
            });
            return false;//阻止表单跳转
        });

        //表单赋值
        layui.$('#LAY-component-form-setval').on('click', function () {
            var content = layedit.getContent(editIndex)
            console.log("content=>", content)

            var loading_index = layer.load(0, {shade: false});
            $.ajax({
                url: "{% url 'writing:generate'%}",
                type: 'post',
                data: {'content': content},
                dataType: "text",
                success: function (result) {
                    // console.log(data)
                    var obj = eval("(" + result + ")");

                    if (obj.code === 100) {
                        layer.msg('生成成功', {icon: 1});
                        form.val('edit', {
                            "title": obj.title,
                            "abstract": obj.summary,
                            "keyword": obj.keyword,
                        });
                    } else {
                        layer.msg('生成失败', {icon: 2});
                    }
                    layer.close(loading_index);
                }
            });


        });

        $('#back').on('click', function () {
            window.location.href = '{% url 'writing:list' %}';
        });

    });
</script>


</html>

3-2-应用软件开发实践/83012852源码完整/EasyWriting/writing/templates/writing/help.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>写作小助手-使用指南</title>
</head>
{% load static %}
<script src="{% static 'scripts/jquery-1.7.2.js' %}"></script>
<link rel="stylesheet" type="text/css" href="{% static 'layui/css/layui.css' %}">
<body>
<div class="layui-header">
    <ul class="layui-nav">
        <li class="layui-nav-item"><a href="{% url 'writing:index' %}">主页</a></li>
        <li class="layui-nav-item"><a href="{% url 'writing:list' %}">写作台</a></li>
        <li class="layui-nav-item layui-this"><a href="">使用指南</a></li>
        <li class="layui-nav-item"><a href="{% url 'writing:about' %}">关于</a></li>
    </ul>
    <ul class="layui-nav layui-layout-right">
        <li class="layui-nav-item layui-hide layui-show-md-inline-block">
            <a href="javascript:;">
                <img id='iconNav' src="{% static 'media/web/icon.jpg' %}" class="layui-nav-img">
                欢迎您，{{ username }}！
            </a>
            <dl class="layui-nav-child">
                <dd><a href="{% url 'writing:user' %}">修改信息</a></dd>
                <dd><a href="{% url 'user:logout' %}">退出登录</a></dd>
            </dl>
        </li>
    </ul>
</div>

<div style="margin: 10px">
    <div style="margin: 10px">
        <blockquote class="layui-elem-quote layui-text">
            这里是用户写作平台的使用指南，可以查看平台的使用方法。
        </blockquote>
        <iframe class="pdf" src="{% static 'media/pdf/help_document.pdf' %}" style = "width:100%;
    height:600px; border: none"></iframe>
    </div>
</div>


</body>
<script src="{% static 'layui/layui.js' %}"></script>
</html>

3-2-应用软件开发实践/83012852源码完整/EasyWriting/writing/templates/writing/user.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>文章新建</title>
</head>

{#  注意引入文件的方式  #}
{% load static %}
<script src="{% static 'scripts/jquery-1.7.2.js' %}"></script>
<link rel="stylesheet" type="text/css" href="{% static 'layui/css/layui.css' %}">
<body>
<div class="layui-header">
    <ul class="layui-nav">
        <li class="layui-nav-item"><a href="{% url 'writing:index' %}">主页</a></li>
        <li class="layui-nav-item"><a href="{% url 'writing:list' %}">写作台</a></li>
        <li class="layui-nav-item"><a href="{% url 'writing:help' %}">使用指南</a></li>
        <li class="layui-nav-item"><a href="{% url 'writing:about' %}">关于</a></li>
    </ul>
    <ul class="layui-nav layui-layout-right">
        <li class="layui-nav-item layui-hide layui-show-md-inline-block">
            <a href="javascript:;">
                <img id='iconNav' src="{% static 'media/web/icon.jpg' %}" class="layui-nav-img">
                欢迎您，{{ user.username }}！
            </a>
            <dl class="layui-nav-child">
                <dd><a href="">修改信息</a></dd>
                <dd><a href="{% url 'user:logout' %}">退出登录</a></dd>
            </dl>
        </li>
    </ul>
</div>
<div style="margin: 10px">
    <blockquote class="layui-elem-quote layui-text">
        这里可以修改用户的密码。
    </blockquote>

    <fieldset class="layui-elem-field layui-field-title" style="margin-top: 20px;">
        <legend>用户信息修改</legend>
    </fieldset>

    <form class="layui-form" action="" lay-filter="user_edit">
        {% csrf_token %}
        <div class="layui-form-item">
            <div class="layui-inline">
                <label class="layui-form-label">输入旧密码</label>
                <div class="layui-input-inline">
                    <input type="password" name="old_password" autocomplete="off" class="layui-input">
                </div>
            </div>
        </div>

        <div class="layui-form-item">
            <div class="layui-inline">
                <label class="layui-form-label">输入新密码</label>
                <div class="layui-input-inline">
                    <input type="password" name="new_password" lay-verify="new_password" autocomplete="off"
                           class="layui-input">
                </div>
            </div>
        </div>

        <div class="layui-form-item">
            <div class="layui-inline">
                <label class="layui-form-label">再次输入</label>
                <div class="layui-input-inline">
                    <input type="password" name="repeat_password" autocomplete="off" class="layui-input">
                </div>
            </div>
        </div>

        <div class="layui-form-item">
            <div class="layui-input-block">
                <button type="submit" class="layui-btn" lay-submit="" lay-filter="btn_edit">立即提交</button>
            </div>
        </div>


    </form>
</div>


</body>
<script src="{% static 'layui/layui.js' %}"></script>

<script>
    layui.use(['form', 'layedit'], function () {
        var form = layui.form;

        //自定义验证规则
        form.verify({
            new_password: function (value) {
                var passwordPatt = /^\w{5,12}$/;
                if (!passwordPatt.test(value)) {
                    return "密码不合法：密码应长度5到12位，仅含字母，数字下划线";
                }
            },
        });


        //提交事件
        form.on('submit(btn_edit)', function (data) {
            {#layer.alert(JSON.stringify(data.field), {#}
            {#    title: '最终的提交信息'#}
            {# })#}
            $.ajax({
                url: "{% url 'writing:user_update' %}",
                type: 'post',
                data: data.field,
                dataType: "text",
                success: function (result) {
                    // console.log(data)
                    console.log("result: " + result)
                    if (result === 'success') {
                        layer.msg('提交成功', {icon: 1});
                        location.reload();
                    } else {
                        layer.msg(result, {icon: 2});
                    }
                }
            });
            return false;//阻止表单跳转
        });
    });


</script>


</html>